### ISSUE TITLE
Is `compile_slo` still valid?

### ISSUE THREAD

**Issue by jserv** [Kimplul/copyjit#4]
I attempted to apply the following changes:
```diff
--- a/src/copyjit.c
+++ b/src/copyjit.c
@@ -336,13 +336,6 @@ static void select_addiy(ctx_t *ctx, uint8_t i)
        }
 }
 
-static void select_slo(ctx_t *ctx, uint8_t i)
-{
-       switch (i) {
-               SELECT64(ctx, compile_slo);
-       }
-}
-
 void *compile_fast_lio(ctx_t *ctx, unsigned long i)
 {
        void *pc = ctx->pc;
@@ -451,14 +444,6 @@ void *compile_fast_addiy(ctx_t *ctx, unsigned long i)
        return pc;
 }
 
-void *compile_slo(ctx_t *ctx, unsigned long i)
-{
-       assert(i < 64);
-       void *pc = ctx->pc;
-       select_slo(ctx, i);
-       return pc;
-}
-
 void compile_start(ctx_t *ctx)
 {
        /* random number for now */
```

And, the copyjit still builds without regressions. Is `compile_slo` still valid?

**Comment by Kimplul** [comment]
If you mean 'valid' as in is `compile_slo` still callable after your modifications, then no. Only `compile_slo0` through `compile_slo63` are defined as operations, and `compile_slo` is just a wrapper that chooses the correct operation for a runtime parameter `i`.

Everything still compiles and tests pass because `compile_slo` isn't actually used by anything, at least at the moment. Tests are pretty lacking so there are a number of theses kinds of oversights.

Alternatively, if you mean more generally if `compile_slo0` through `compile_slo63` are still 'valid' then sure. In fact, it seems that `compile_slo(&ctx, 1)` is more difficult to inline than `compile_slo1(&ctx)`, leading to slower jit compilation times. As such, you might even want to ban the usage of `compile_slo` if your use case permits in, in which case removing it completely might even be preferable. Similar to `copy-and-patch`, custom operations are fairly easy to create so each project could have their own set of operations, the ones I have here are mostly just to demonstrate how one possible set could be built up.

**Comment by jserv** [comment]
I express my gratitude for the enlightening response, from which I have gained insights into the intricacies of copy-and-patch implementation.
